atividades/aula01/aula01/Models/ErrorViewModel.cs
namespace aula01.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

atividades/aula01/aula01/Models/Variaveis.cs
using System;
using System.Formats.Asn1;

public class Variaveis
{
    //Anotações de tipos
    public int userCount;

    //Uma variavel pode ser declarada
    //e nao inicializada
    public int totalCount;

    // CONSTANTES
    // para declarar uma constante
    // utilizamos a palavra-chave CONST
    // No entanto a CONST deve ser inicializada
    // quando declarada
    const int interestRate = 10;

    //o metodo construtor e invocado
    //na inicialização do objeto por meio
    // da palavra reservada new
    // Por regra, o construtor sempre tem
    // o mesmo nome da classe
    public Variaveis()
	{
        totalCount = 0;

        //tipo implícito
        // a palavvra chave var se encarrega
        // de definir o tipo da variável
        // na instrução de atribuição
        var signalStrength = 22;
        var companyName = "ACME";
	}
}

atividades/aula01/aula01/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using aula01.Models;

namespace aula01.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        Variaveis minhaVariavel = new Variaveis();

        return View(minhaVariavel);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

atividades/aula01/aula01/Controllers/TesteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;

namespace aula01.Controllers
{
    public class Result
    {
        public string Texto = string.Empty;
    }
    public class TesteController : Controller
    {
        private readonly ILogger<TesteController> _logger;

        public TesteController(
            ILogger<TesteController> logger
            )
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View("Index", new Result());
        }
        
        [HttpPost]
        public IActionResult Index(string texto)
        {
            Result resultado = new Result();

            int criptografia = Convert.ToInt32(texto) + 5;
            int letra
            if (int letra > 122) { letra = letra - 26; }
            //converte ascii para char 
            criptografia += Convert.ToChar(letra);
        }

            return View("Index", resultado);
        }
    }
}

atividades/aula01/aula01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aula01</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/aula01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">aula01</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - aula01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

atividades/aula01/aula01/Views/Teste/Index.cshtml
@model aula01.Controllers.Result;

<h1>Controller: Teste</h1>
<h2>Método Index</h2>
<h3>View Index</h3>

<hr />

<form method="post" asp-action="Index" asp-controller="Teste">
    <input type="text" id="texto" name="texto" />
    <input type="submit" value="Postar" />
</form>

<hr />

@if(!string.IsNullOrEmpty(Model.Texto))
{
    <div>
        <span>Texto convertido: </span>
        <strong>@Model.Texto</strong>
    </div>
}

atividades/aula01/aula01/Views/Teste/Teste.cshtml
@{

}

<h1>Controller: Teste</h1>
<h2>Método Index</h2>
<h3>View Teste</h3>